FROM node:16.10.0-alpine

#RUN mkdir /usr/src/app 
 
WORKDIR /usr/src/app

RUN npm install -g @angular/cli 

COPY . . 

RUN npm install

EXPOSE 4200

CMD [ "ng", "serve", "--host", "0.0.0.0", "--poll=2000", "--port", "4200", "--disable-host-check" ]'